export const URL_POPULAR = '/movie/popular'
export const URL_NOW_PLAYING = '/movie/now_playing'
export const URL_UPCOMING = '/movie/upcoming'
export const URL_TOP_RATED = '/movie/top_rated'
export const URL_GENRES = '/genre/movie/list'
export const URL_SEARCH = '/search/movie'
